### PR TITLE
fixed cran checks

### PR DESCRIPTION
**Pull request by earowang**

### CODE REVIEW

**Comment by earowang** [comment]
Looks like you've fixed some notes/warning. It passed the checks on macos.

**Comment by earowang** [comment]
``` r
library(fable)
#> Loading required package: fablelite
library(tsibble)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following object is masked from 'package:tsibble':
#> 
#>     id
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(feasts)
#> 
#> Attaching package: 'feasts'
#> The following object is masked from 'package:grDevices':
#> 
#>     X11

vic_food <- tsibbledata::aus_retail %>% 
  filter(State == "Victoria", Industry == "Food retailing")
my_dcmp_spec <- dcmp_model(
  STL, log(Turnover) ~ season(window = Inf),
  ARIMA(seas_adjust), SNAIVE(season_year)
)

vic_food %>%
  model(my_dcmp_spec) %>% 
  forecast(h="5 years") %>% 
  autoplot(vic_food)
#> Error in UseMethod("augment"): no applicable method for 'augment' applied to an object of class "model_combination"
```

<sup>Created on 2019-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
This is fixed in changes to master.

**Comment by earowang** [comment]
Okay. I can reproduce the same error on my linux server.

**Comment by earowang** [comment]
I can confirm that it roots in tsibble.

**Comment by earowang** [comment]
Actually it goes further down to dplyr https://github.com/tidyverse/dplyr/issues/4259 we just happed to use dplyr dev version.

**Pull request merged**
